# Generated by Django 2.1.3 on 2018-12-12 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forumid', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('forumname', models.CharField(max_length=30, verbose_name='Name')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('viewprivacy', models.IntegerField(choices=[(1, 'Everyone'), (2, 'People who are logged in.'), (3, 'Only You')], default=1, verbose_name='Who can view this forum')),
                ('writeprivacy', models.IntegerField(choices=[(1, 'People who are logged in'), (2, 'Only You')], default=1, verbose_name='Who can create topics in this forum')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('creatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('content', models.TextField(verbose_name='Content')),
                ('creatorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicid', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=50, verbose_name='Name')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('viewprivacy', models.IntegerField(choices=[(1, 'Everyone'), (2, 'People who are logged in.'), (3, 'Only You')], default=1, verbose_name='Who can view this topic')),
                ('writeprivacy', models.IntegerField(choices=[(1, 'Everyone'), (2, 'People who are logged in.'), (3, 'Only You')], default=1, verbose_name='Who can post in this topic')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('creatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('forumid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Forum')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topicid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Topic', verbose_name='Topic'),
        ),
    ]
